### ISSUE TITLE
Node应用内存占用过高，然后超出内存限制

### ISSUE THREAD

**Issue by axetroy** [axetroy/stackoverflow#23]
64位系统 1.4GB，32位系统 0.7GB，是V8虚拟机的默认堆大小限制，因为考虑V8虚拟机的垃圾回收效率。

在使用Nuxt开发过程中，不知道什么原因，内存占用到1.2+G

当变更文件时，重新打包，内存上涨到1.4-1.5G。

超出内存限制然后崩溃

暂行的解决办法，提高V8的内存占用

```
node --max-old-space-size=4096 ./node_modules/.bin/nuxt dev
```

**Comment by LeonDWong** [comment]
@axetroy 你好，我也遇到同样的问题，请问你解决了吗？我的 nuxt 版本也是 1.4.x，然后内存暴增的原因是 string 和 array 缓存
