### ISSUE TITLE
Nuxt在更新后，旧的页面还存在，跳转链接的时候失败

### ISSUE THREAD

**Issue by axetroy** [axetroy/stackoverflow#26]
因为旧的URL已经不存在

**Comment by axetroy** [comment]
已解决:
https://github.com/nuxt/nuxt.js/pull/3940#event-2036348112

**Comment by main2018** [comment]
@axetroy 旧的页面还存在 是什么意思， 我现在也遇到了问题，目录结构是这样的
![image](https://user-images.githubusercontent.com/28427901/50677643-e69ef900-1035-11e9-9271-25c7c95e71b6.png)
当我从 / 跳到 detail 再跳到 about时 就出错， 
错误信息： Loading chunk pages_detail__id failed.

想问下怎么解决，谢谢，这问题困扰了我两天了，如果看到尽快回复，万分感谢
