### ISSUE TITLE
nuxt.js 服务端渲染没法做序列化的嵌套页面渲染

### ISSUE THREAD

**Issue by axetroy** [axetroy/stackoverflow#7]
例如页面A

包含了路由a，a路由包含子路由a.1

a 路由有异步fetch，a.1路由也有异步fetch.

遗憾的是，现在是并发fetch，并没有序列化.

截止目前，还没有一个很好的解决方案.

后续官方可能会支持

https://github.com/nuxt/nuxt.js/issues/2825

**Comment by cnlinjie** [comment]
现在还是没有吗？
